[package]
name = "nomin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "0.3"
handlebars = "4.1.0"
serde_json = "1.0"
regex = "1"
serde = "1.0.126"

